Repository depromeet/antoon-api, pull requests merged in 2022-06, with the labels that each got.

#132 🐛[Fix/recommendation-128] 탑승/하차 API 반환값 추가 및 리팩토링
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
  src/main/java/kr/co/antoon/recommendation/domain/vo/RecommendationStatus.java
  src/main/java/kr/co/antoon/recommendation/dto/response/RecommendationResponse.java
  src/main/java/kr/co/antoon/recommendation/facade/RecommendationFacade.java
  src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java
Labels: fix, refactor

#139 :bug: [Fix/webtoon-detail-130] 웹툰 상세 조회 시 scoreGap, 랭킹, 탑승하차 상태 추가
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/webtoon/converter/WebtoonConverter.java
  src/main/java/kr/co/antoon/webtoon/dto/WebtoonDto.java
  src/main/java/kr/co/antoon/webtoon/dto/query/WebtoonNativeDto.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
Labels: fix

#141 ✅ [Test/all-140] 테스트 코드 작성 및 잘못된 비즈니스 로직 수정
  src/main/java/kr/co/antoon/common/presentation/HealthController.java
  src/main/java/kr/co/antoon/criteria/BasicAllocateScore.java
  src/main/java/kr/co/antoon/feedback/application/FeedbackService.java
  src/main/java/kr/co/antoon/feedback/domain/Feedback.java
  src/main/java/kr/co/antoon/feedback/domain/vo/Score.java
  src/main/java/kr/co/antoon/feedback/domain/vo/Status.java
  src/main/java/kr/co/antoon/feedback/dto/FeedbackResponse.java
  src/main/java/kr/co/antoon/feedback/infrastructure/FeedbackRepository.java
  src/test/java/kr/co/antoon/common/presentation/HealthControllerTest.java
  src/test/java/kr/co/antoon/common/presentation/SwaggerControllerTest.java
  src/test/java/kr/co/antoon/common/util/CommonUtilTest.java
  src/test/java/kr/co/antoon/criteria/BasicAllocateScoreTest.java
  src/test/java/kr/co/antoon/discussion/domain/DiscussionLikeTest.java
  src/test/java/kr/co/antoon/discussion/domain/DiscussionTest.java
  src/test/java/kr/co/antoon/feedback/application/FeedbackServiceTest.java
  src/test/java/kr/co/antoon/feedback/domain/FeedbackTest.java
  src/test/java/kr/co/antoon/feedback/domain/vo/ScoreTest.java
  src/test/java/kr/co/antoon/feedback/facade/FeedbackFacadeTest.java
  src/test/java/kr/co/antoon/feedback/presentation/FeedbackControllerTest.java
  src/test/java/kr/co/antoon/graph/domain/vo/GraphStatusTest.java
  src/test/java/kr/co/antoon/recommendation/domain/RecommendationCountTest.java
Labels: improve, fix, test

#135 🐛[Fix/patchMypage] 마이페이지 수정 api 분리
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/domain/User.java
  src/main/java/kr/co/antoon/user/dto/request/UserDetailImage.java
  src/main/java/kr/co/antoon/user/dto/request/UserDetailName.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
Labels: fix

#145 ⚡️ [Improve/main-page-api-142] top3 장르 조회 로직 수정 (top3 -> 임의값)
  src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonGenreService.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonGenreAllResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonGenreRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: improve

#149 ⚡️ [Improve/all-148] 앙뚜앙 대격변
  scripts/sql/DDL.sql
  src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
  src/main/java/kr/co/antoon/coin/domain/AntCoinHistory.java
  src/main/java/kr/co/antoon/coin/domain/AntCoinWallet.java
  src/main/java/kr/co/antoon/coin/domain/vo/RemittanceStatus.java
  src/main/java/kr/co/antoon/coin/domain/vo/RemittanceType.java
  src/main/java/kr/co/antoon/coin/domain/vo/WalletStatus.java
  src/main/java/kr/co/antoon/coin/infrastructure/AntCoinHistoryRepository.java
  src/main/java/kr/co/antoon/coin/infrastructure/AntCoinWalletRepository.java
  src/main/java/kr/co/antoon/common/dto/PageDto.java
  src/main/java/kr/co/antoon/config/ScoreAllocationCriteriaConfig.java
  src/main/java/kr/co/antoon/config/SecurityConfig.java
  src/main/java/kr/co/antoon/crawling/KakaoWebtoonCrawling.java
  src/main/java/kr/co/antoon/crawling/NaverWebtoonCrawling.java
  src/main/java/kr/co/antoon/crawling/dto/WebtoonCrawlingDto.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionLikeService.java
  src/main/java/kr/co/antoon/discussion/domain/DiscussionLike.java
  src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
  src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
  src/main/java/kr/co/antoon/oauth/application/AuthService.java
  src/main/java/kr/co/antoon/oauth/config/LoginUserArgumentResolver.java
  src/main/java/kr/co/antoon/recommendation/domain/vo/RecommendationStatus.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
  src/main/java/kr/co/antoon/webtoon/converter/WebtoonConverter.java
  src/main/java/kr/co/antoon/webtoon/dto/WebtoonDto.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonPublishDayRepository.java
  src/test/java/kr/co/antoon/user/domain/vo/GenderTest.java
  src/test/java/kr/co/antoon/user/domain/vo/RoleTest.java
  src/test/java/kr/co/antoon/webtoon/domain/WebtoonTest.java
  src/test/java/kr/co/antoon/webtoon/domain/vo/GenreCategoryTest.java
Labels: improve, fix, feature

#153 ⚡️ [Feature/mvp-2-150] 코인 지갑 및 기록 추적 기능
  src/main/java/kr/co/antoon/coin/application/AntCoinHistoryService.java
  src/main/java/kr/co/antoon/coin/application/AntCoinWalletService.java
  src/main/java/kr/co/antoon/coin/domain/AntCoinHistory.java
  src/main/java/kr/co/antoon/coin/domain/vo/RemittanceType.java
  src/main/java/kr/co/antoon/coin/facade/AntCoinFacade.java
  src/main/java/kr/co/antoon/coin/infrastructure/AntCoinWalletRepository.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
Labels: feature

#151 [Fix/patchMypage] 마이페이지 조회 시 userId 추가 반환
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/dto/response/UserDetailResponse.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
Labels: fix, refactor

#162 :sparkles: [feature/coin-recommend] 탑승/하차를 통한 코인 지급 로직 구현
  src/main/java/kr/co/antoon/coin/application/AntCoinHistoryService.java
  src/main/java/kr/co/antoon/coin/application/AntCoinWalletService.java
  src/main/java/kr/co/antoon/coin/domain/AntCoinHistory.java
  src/main/java/kr/co/antoon/coin/facade/AntCoinFacade.java
  src/main/java/kr/co/antoon/coin/infrastructure/AntCoinHistoryRepository.java
  src/main/java/kr/co/antoon/coin/infrastructure/AntCoinWalletRepository.java
  src/main/java/kr/co/antoon/recommendation/dto/response/RecommendationResponse.java
  src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java
Labels: feature

#161 ✨[Feature/characterVote-158] 인물,커플 TOP30 조회 및 투표 구현
  src/main/java/kr/co/antoon/common/presentation/HealthController.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/subject/application/SubjectRecommendationService.java
  src/main/java/kr/co/antoon/subject/application/SubjectService.java
  src/main/java/kr/co/antoon/subject/domain/Subject.java
  src/main/java/kr/co/antoon/subject/domain/SubjectRecommendation.java
  src/main/java/kr/co/antoon/subject/domain/vo/SubjectType.java
  src/main/java/kr/co/antoon/subject/dto/response/CharacterResponse.java
  src/main/java/kr/co/antoon/subject/dto/response/CoupleResponse.java
  src/main/java/kr/co/antoon/subject/facade/SubjectFacade.java
  src/main/java/kr/co/antoon/subject/facade/SubjectRecommendationFacade.java
  src/main/java/kr/co/antoon/subject/infrastructure/SubjectRecommendationRepository.java
  src/main/java/kr/co/antoon/subject/infrastructure/SubjectRepository.java
  src/main/java/kr/co/antoon/subject/presentation/SubjectController.java
  src/main/java/kr/co/antoon/subject/presentation/SubjectRecommendationController.java
  src/test/java/kr/co/antoon/subject/application/SubjectRecommendationTest.java
  src/test/java/kr/co/antoon/subject/application/SubjectServiceTest.java
  src/test/java/kr/co/antoon/subject/domain/SubjectTest.java
  src/test/java/kr/co/antoon/subject/facade/SubjectFacadeTest.java
Labels: feature

#180 ✨[Feature/s3image upload] S3 이미지 업로드 구현 (마이페이지도 이미지 업로드 방식으로 수정)
  build.gradle
  src/main/java/kr/co/antoon/aws/application/AwsS3Service.java
  src/main/java/kr/co/antoon/aws/domain/vo/S3Category.java
  src/main/java/kr/co/antoon/aws/presentation/AdminController.java
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/config/SecurityConfig.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
Labels: feature

#171 :zap: [improve/login-addDomain] 구글 로그인 추가
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
Labels: improve

#179 ✨ [Feature/vote 163] 커뮤니티 페이지 > 개미들의 선택 목록 조회 구현
  src/main/java/kr/co/antoon/vote/application/CandidateService.java
  src/main/java/kr/co/antoon/vote/application/TopicService.java
  src/main/java/kr/co/antoon/vote/application/VoteService.java
  src/main/java/kr/co/antoon/vote/domain/Candidate.java
  src/main/java/kr/co/antoon/vote/domain/Topic.java
  src/main/java/kr/co/antoon/vote/domain/Vote.java
  src/main/java/kr/co/antoon/vote/dto/response/TopicChoicesResponse.java
  src/main/java/kr/co/antoon/vote/dto/response/TopicResponse.java
  src/main/java/kr/co/antoon/vote/facade/TopicFacade.java
  src/main/java/kr/co/antoon/vote/facade/VoteFacade.java
  src/main/java/kr/co/antoon/vote/infrastructure/TopicRepository.java
  src/main/java/kr/co/antoon/vote/presentation/TopicController.java
  src/main/java/kr/co/antoon/vote/presentation/VoteController.java
Labels: feature

#184 ✨ [Feature/vote-comment-174] 투표 페이지 댓글 CRUD 및 좋아요 기능 구현
  src/main/java/kr/co/antoon/vote/application/TopicDiscussionLikeService.java
  src/main/java/kr/co/antoon/vote/application/TopicDiscussionService.java
  src/main/java/kr/co/antoon/vote/application/TopicService.java
  src/main/java/kr/co/antoon/vote/converter/TopicDiscussionConverter.java
  src/main/java/kr/co/antoon/vote/domain/Candidate.java
  src/main/java/kr/co/antoon/vote/domain/Topic.java
  src/main/java/kr/co/antoon/vote/domain/TopicDiscussion.java
  src/main/java/kr/co/antoon/vote/domain/TopicDiscussionLike.java
  src/main/java/kr/co/antoon/vote/domain/Vote.java
  src/main/java/kr/co/antoon/vote/dto/request/TopicDiscussionCreateRequest.java
  src/main/java/kr/co/antoon/vote/dto/request/TopicDiscussionUpdateRequest.java
  src/main/java/kr/co/antoon/vote/dto/response/TopicAllResponse.java
  src/main/java/kr/co/antoon/vote/dto/response/TopicDiscussionResponse.java
  src/main/java/kr/co/antoon/vote/dto/response/TopicResponse.java
  src/main/java/kr/co/antoon/vote/facade/TopicFacade.java
  src/main/java/kr/co/antoon/vote/infrastructure/TopicDiscussionLikeRepository.java
  src/main/java/kr/co/antoon/vote/infrastructure/TopicDiscussionRepository.java
  src/main/java/kr/co/antoon/vote/presentation/TopicController.java
  src/main/java/kr/co/antoon/vote/presentation/VoteController.java
Labels: feature

#186 ✨ [Feature/cache 185] 캐시 추가
  src/main/java/kr/co/antoon/cache/webtoon/WebtoonRedisCacheService.java
  src/main/java/kr/co/antoon/cache/webtoon/WebtoonRedisKey.java
  src/main/java/kr/co/antoon/config/RedisConfig.java
  src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
  src/main/java/kr/co/antoon/graph/facade/TopRankFacade.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
Labels: feature

#178 ✨[Feature/Character-detail-176] 인물/커플 상세조회 구현
  scripts/sql/DDL.sql
  src/main/java/kr/co/antoon/character/application/CharacterHistoryService.java
  src/main/java/kr/co/antoon/character/application/CharacterImageService.java
  src/main/java/kr/co/antoon/character/application/CharacterService.java
  src/main/java/kr/co/antoon/character/domain/Character.java
  src/main/java/kr/co/antoon/character/domain/CharacterImage.java
  src/main/java/kr/co/antoon/character/domain/vo/CharacterImageType.java
  src/main/java/kr/co/antoon/character/dto/reqeust/CharacterImageRequest.java
  src/main/java/kr/co/antoon/character/dto/reqeust/CharacterRequest.java
  src/main/java/kr/co/antoon/character/dto/response/CharacterDetailResponse.java
  src/main/java/kr/co/antoon/character/dto/response/CharacterResponse.java
  src/main/java/kr/co/antoon/character/dto/response/CoupleResponse.java
  src/main/java/kr/co/antoon/character/facade/CharacterFacade.java
  src/main/java/kr/co/antoon/character/facade/CharacterHistoryFacade.java
  src/main/java/kr/co/antoon/character/infrastructure/CharacterHistoryRepository.java
  src/main/java/kr/co/antoon/character/infrastructure/CharacterImageRepository.java
  src/main/java/kr/co/antoon/character/infrastructure/CharacterRepository.java
  src/main/java/kr/co/antoon/character/presentation/CharacterController.java
  src/main/java/kr/co/antoon/character/presentation/CharacterHistoryController.java
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionLikeService.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/dto/query/WebtoonCharacterNativeDto.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
  src/test/java/kr/co/antoon/character/application/CharacterHistoryServiceTest.java
  src/test/java/kr/co/antoon/character/application/CharacterServiceTest.java
  src/test/java/kr/co/antoon/character/domain/CharacterTest.java
  src/test/java/kr/co/antoon/character/facade/CharacterFacadeTest.java
  src/test/java/kr/co/antoon/like/application/LikeServiceTest.java
Labels: feature

#175 :zap: [improve/coin-limit] 웹툰 탑승/하차를 통한 코인 보상 횟수 제한
  src/main/java/kr/co/antoon/character/facade/CharacterHistoryFacade.java
  src/main/java/kr/co/antoon/coin/AntCoinClient.java
  src/main/java/kr/co/antoon/coin/application/AntCoinHistoryService.java
  src/main/java/kr/co/antoon/coin/application/AntCoinService.java
  src/main/java/kr/co/antoon/coin/domain/vo/CoinRewardType.java
  src/main/java/kr/co/antoon/coin/domain/vo/RemittanceType.java
  src/main/java/kr/co/antoon/coin/dto/CoinReason.java
  src/main/java/kr/co/antoon/coin/infrastructure/AntCoinHistoryRepository.java
  src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java
  src/main/java/kr/co/antoon/vote/facade/VoteFacade.java
Labels: improve

#173 :sparkles: [feature/mypageCoin] 마이페이지 조회 시 코인 수, 랭크 데이터 추가
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/dto/response/GetUserDetailResponse.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
Labels: feature

#188 ✨[Feature/character-discussion-77] 인물/커플 댓글 구현
  src/main/java/kr/co/antoon/character/application/CharacterDiscussionLikeService.java
  src/main/java/kr/co/antoon/character/application/CharacterDiscussionService.java
  src/main/java/kr/co/antoon/character/application/CharacterService.java
  src/main/java/kr/co/antoon/character/domain/CharacterDiscussion.java
  src/main/java/kr/co/antoon/character/domain/CharacterDiscussionLike.java
  src/main/java/kr/co/antoon/character/dto/reqeust/CharacterDiscussionRequest.java
  src/main/java/kr/co/antoon/character/dto/response/CharacterDetailResponse.java
  src/main/java/kr/co/antoon/character/dto/response/CharacterDiscussionResponse.java
  src/main/java/kr/co/antoon/character/dto/response/CharacterResponse.java
  src/main/java/kr/co/antoon/character/facade/CharacterDiscussionFacade.java
  src/main/java/kr/co/antoon/character/facade/CharacterDiscussionLikeFacade.java
  src/main/java/kr/co/antoon/character/infrastructure/CharacterDiscussionLikeRepository.java
  src/main/java/kr/co/antoon/character/infrastructure/CharacterDiscussionRepository.java
  src/main/java/kr/co/antoon/character/presentation/CharacterDiscussionController.java
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
Labels: feature

#144 ✨ [Feature/profile-image-110] 프로필 기본 이미지 조회
  build.gradle
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/config/AwsS3Config.java
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/dto/response/UserProfileResponse.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
  src/main/resources/logback-spring.xml
Labels: feature

#202 ⚡️ [Fix/community vote] 투표 API 반환값에 투표종료 여부 추가 및 중복투표 방지 로직 추가
  src/main/java/kr/co/antoon/common/dto/ResponseDto.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/vote/application/VoteService.java
  src/main/java/kr/co/antoon/vote/domain/Topic.java
  src/main/java/kr/co/antoon/vote/dto/response/TopicResponse.java
  src/main/java/kr/co/antoon/vote/facade/TopicFacade.java
  src/main/java/kr/co/antoon/vote/facade/VoteFacade.java
  src/main/java/kr/co/antoon/vote/infrastructure/VoteRepository.java
  src/main/java/kr/co/antoon/vote/presentation/TopicController.java
  src/main/java/kr/co/antoon/vote/presentation/TopicDiscussionController.java
  src/main/java/kr/co/antoon/vote/presentation/VoteController.java
Labels: improve
