Repository depromeet/antoon-api, pull requests merged in 2022-04, with the labels that each got.

#4 🐛 [Fix/common-3] 공통기능 수정
  .github/ISSUE_TEMPLATE/toon-zip-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  build.gradle
  scripts/DDL.sql
  src/main/java/kr/co/toonzip/common/entity/BaseEntity.java
  src/main/java/kr/co/toonzip/common/presentation/HealthController.java
  src/main/java/kr/co/toonzip/common/presentation/SwaggerController.java
  src/main/java/kr/co/toonzip/config/CorsConfig.java
  src/main/java/kr/co/toonzip/config/JpaAuditingConfig.java
  src/main/java/kr/co/toonzip/config/SwaggerConfig.java
  src/main/java/kr/co/toonzip/config/data/SwaggerNote.java
  src/main/java/kr/co/toonzip/config/properties/CorsProperties.java
  src/main/resources/config/application.yml
Labels: fix

#7 ✨ [Feature/webtoon-crawling-5] 네이버 웹툰 크롤링 구현
  build.gradle
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonBatchScheduler.java
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonDailyJob.java
  src/main/java/kr/co/antoon/common/domain/BaseEntity.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonSnapshotService.java
  src/main/java/kr/co/antoon/webtoon/crawling/NaverWebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/crawling/WebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/crawling/WebtoonCrawlingValue.java
  src/main/java/kr/co/antoon/webtoon/domain/Webtoon.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonPublishDay.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonSnapshot.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/Platform.java
  src/main/java/kr/co/antoon/webtoon/dto/WebtoonCrawlingDto.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonPublishDayRepository.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonSnapshotRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: feature

#15 ♻️ [Refactor/webtoon-8] 웹툰 크롤링 리펙토링
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonGenreService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonSnapshotService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonWriterService.java
  src/main/java/kr/co/antoon/webtoon/crawling/NaverWebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/domain/Webtoon.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonGenre.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonWriter.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/Category.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/Platform.java
  src/main/java/kr/co/antoon/webtoon/dto/WebtoonCrawlingDto.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonGenreRepository.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonWriterRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: refactor

#17 ✨ [Feature/discussion-12] 종토방 기능 구현
  .github/workflows/gradle.yml
  src/main/java/kr/co/antoon/common/dto/ResponseDto.java
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/discussion/domain/Discussion.java
  src/main/java/kr/co/antoon/discussion/dto/request/DiscussionCreateRequest.java
  src/main/java/kr/co/antoon/discussion/dto/request/DiscussionUpdateRequest.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionCreateResponse.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionReadResponse.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionUpdateResponse.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
  src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
  src/main/java/kr/co/antoon/error/GlobalExceptionHandler.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/error/exception/common/NotExistsException.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/test/java/kr/co/antoon/AntoonApplicationTests.java
  src/test/java/kr/co/antoon/discussion/application/DiscussionServiceTest.java
Labels: feature

#23 ♻️ [Refactor/webtoon-crawling-19] 웹툰 크롤링 및 기능 수정
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonBatchScheduler.java
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonDailyJob.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/error/exception/common/NotExistsException.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/crawling/NaverWebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/crawling/WebtoonCrawlingFactory.java
  src/main/java/kr/co/antoon/webtoon/crawling/WebtoonCrawlingValue.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/Platform.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: refactor

#22 ✨ [Feature/OAuth2.0] Spring Security를 활용한 kakao 로그인 구현
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  src/main/java/kr/co/antoon/config/SecurityConfig.java
  src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/oauth/application/TokenService.java
  src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
  src/main/java/kr/co/antoon/oauth/dto/TokenDto.java
  src/main/java/kr/co/antoon/oauth/dto/UserDto.java
  src/main/java/kr/co/antoon/oauth/dto/UserRequestMapper.java
  src/main/java/kr/co/antoon/oauth/filter/JwtAuthFilter.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
  src/main/java/kr/co/antoon/user/domain/User.java
  src/main/java/kr/co/antoon/user/infrastructure/UserRepository.java
  src/main/resources/config/application.yml
Labels: feature

#20 ✨ [Feature/oauth2.0] 카카오 소셜로그인 구현
  src/main/java/kr/co/antoon/config/SecurityConfig.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/kr/co/antoon/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/co/antoon/security/oauth2/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/security/oauth2/domain/KakaoOAuth2UserInfo.java
  src/main/java/kr/co/antoon/security/oauth2/domain/OAuth2UserInfoFactory.java
  src/main/java/kr/co/antoon/security/oauth2/domain/UserPrincipal.java
  src/main/java/kr/co/antoon/security/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/kr/co/antoon/security/token/JwtFilter.java
  src/main/java/kr/co/antoon/security/token/JwtTokenProvider.java
  src/main/java/kr/co/antoon/user/application/AuthService.java
  src/main/java/kr/co/antoon/user/domain/RefreshToken.java
  src/main/java/kr/co/antoon/user/domain/User.java
  src/main/java/kr/co/antoon/user/domain/vo/ProviderType.java
  src/main/java/kr/co/antoon/user/dto/request/LoginRequest.java
  src/main/java/kr/co/antoon/user/dto/response/TokenResponse.java
  src/main/java/kr/co/antoon/user/exception/TokenExpiredException.java
  src/main/java/kr/co/antoon/user/exception/UserNotExistException.java
  src/main/java/kr/co/antoon/user/infrastructure/RefreshTokenRepository.java
  src/main/java/kr/co/antoon/user/presentation/AuthController.java
  src/main/java/kr/co/antoon/util/CookieUtil.java
  src/test/java/kr/co/antoon/token/JwtTokenTest.java
  src/test/java/kr/co/antoon/user/RefreshTest.java
Labels: feature

#27 ✨[Feature/kakao webtoon crawling-9] 카카오페이지 웹툰 크롤링 및 장르, 콘텐츠 추가 #24
  build.gradle
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonBatchScheduler.java
  src/main/java/kr/co/antoon/webtoon/crawling/KakaoWebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/crawling/WebtoonCrawlingFactory.java
  src/main/java/kr/co/antoon/webtoon/crawling/WebtoonCrawlingValue.java
  src/test/java/kr/co/antoon/webtoon/crawling/KakaoWebtoonCrawlingTest.java
Labels: feature

#25 ✨ [Feature/webtoon-graph-invest-21] 그래프 스냅샷 및 알고리즘 구현
  src/main/java/kr/co/antoon/batch/graph/GraphScoreBatchScheduler.java
  src/main/java/kr/co/antoon/batch/graph/GraphScoreDailyJob.java
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonCrawlingBatchScheduler.java
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonCrawlingDailyJob.java
  src/main/java/kr/co/antoon/common/entity/BaseEntity.java
  src/main/java/kr/co/antoon/config/data/SwaggerNote.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
  src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
  src/main/java/kr/co/antoon/graph/domain/GraphScoreSnapshot.java
  src/main/java/kr/co/antoon/graph/domain/vo/GraphStatus.java
  src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
  src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonSnapshotService.java
  src/main/java/kr/co/antoon/webtoon/crawling/KakaoWebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/domain/Webtoon.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonGenre.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonSnapshot.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonWriter.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/ActiveStatus.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/Category.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonSnapshotRepository.java
  src/main/resources/config/application.yml
Labels: feature
