Repository depromeet/antoon-api, pull requests merged in 2022-05, with the labels that each got.

#35 ✨ [Feature/like] 종토방 좋아요 구현
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/discussion/domain/Discussion.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionCreateResponse.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionReadResponse.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionUpdateResponse.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
  src/main/java/kr/co/antoon/like/application/LikeService.java
  src/main/java/kr/co/antoon/like/domain/Like.java
  src/main/java/kr/co/antoon/like/facade/LikeFacade.java
  src/main/java/kr/co/antoon/like/infrastructure/LikeRepository.java
  src/main/java/kr/co/antoon/like/presentation/LikeController.java
  src/test/java/kr/co/antoon/discussion/application/DiscussionServiceTest.java
  src/test/java/kr/co/antoon/like/application/LikeServiceTest.java
  src/test/java/kr/co/antoon/like/infrastructure/LikeControllerTest.java
Labels: feature

#28 ♻️[ Refactor/OAuth2.0] 카카오 소셜로그인 리펙토링
  build.gradle
  src/main/java/kr/co/antoon/config/SecurityConfig.java
  src/main/java/kr/co/antoon/config/WebConfig.java
  src/main/java/kr/co/antoon/oauth/application/AuthService.java
  src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/oauth/application/JwtTokenProvider.java
  src/main/java/kr/co/antoon/oauth/application/TokenService.java
  src/main/java/kr/co/antoon/oauth/config/LoginUser.java
  src/main/java/kr/co/antoon/oauth/config/LoginUserArgumentResolver.java
  src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
  src/main/java/kr/co/antoon/oauth/dto/TokenDto.java
  src/main/java/kr/co/antoon/oauth/dto/TokenResponse.java
  src/main/java/kr/co/antoon/oauth/dto/UserDto.java
  src/main/java/kr/co/antoon/oauth/dto/UserRequestMapper.java
  src/main/java/kr/co/antoon/oauth/exception/TokenExpiredException.java
  src/main/java/kr/co/antoon/oauth/filter/JwtAuthFilter.java
  src/main/java/kr/co/antoon/oauth/filter/JwtFilter.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/kr/co/antoon/oauth/presentation/AuthController.java
  src/main/java/kr/co/antoon/oauth/presentation/OauthController.java
  src/main/java/kr/co/antoon/security/CurrentUser.java
  src/main/java/kr/co/antoon/security/oauth2/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/security/oauth2/application/CustomUserDetailService.java
  src/main/java/kr/co/antoon/security/oauth2/domain/KakaoOAuth2UserInfo.java
  src/main/java/kr/co/antoon/security/oauth2/domain/OAuth2UserInfo.java
  src/main/java/kr/co/antoon/security/oauth2/domain/UserPrincipal.java
  src/main/java/kr/co/antoon/user/domain/User.java
  src/main/java/kr/co/antoon/user/domain/vo/Role.java
  src/main/java/kr/co/antoon/user/exception/UserNotExistException.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
  src/test/java/kr/co/antoon/token/JwtTokenTest.java
  src/test/java/kr/co/antoon/user/RefreshTest.java
Labels: refactor

#38 ✨ [Feature/onboarding] 탑승해요 하차해요 구현
  build.gradle
  src/main/java/kr/co/antoon/batch/recommendation/RecommendationBatchScheduler.java
  src/main/java/kr/co/antoon/batch/recommendation/RecommendationDailyJob.java
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonCrawlingBatchScheduler.java
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/error/exception/common/AlreadyExistsException.java
  src/main/java/kr/co/antoon/recommendation/application/RecommendationService.java
  src/main/java/kr/co/antoon/recommendation/domain/Recommendation.java
  src/main/java/kr/co/antoon/recommendation/domain/vo/RecommendationStatus.java
  src/main/java/kr/co/antoon/recommendation/facade/RecommendationFacade.java
  src/main/java/kr/co/antoon/recommendation/infrastructure/RecommendationRepository.java
  src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java
  src/main/java/kr/co/antoon/webtoon/domain/Webtoon.java
  src/test/java/kr/co/antoon/recommendation/presentation/RecommendationControllerTest.java
  src/test/java/kr/co/antoon/webtoon/crawling/KakaoWebtoonCrawlingTest.java
Labels: feature

#57 ✨ [Feature/GitHub convention-56] 깃허브 정책 파일 추가
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: feature

#59 ✨ [Feature/crusier-monitoring-58] 모니터링용 슬랙 알림 모듈
  src/main/java/kr/co/antoon/common/domain/SlackCrusier.java
  src/main/java/kr/co/antoon/common/dto/SlackCrusierDto.java
  src/main/java/kr/co/antoon/config/properties/SlackCrusierProperties.java
Labels: feature

#63 🐛 [Fix/cruiser-62] Cruiser 기능 수정 및 통계 모니터링
  src/main/java/kr/co/antoon/batch/cruiser/CruiserBatchScheduler.java
  src/main/java/kr/co/antoon/batch/cruiser/CruiserHourJob.java
  src/main/java/kr/co/antoon/common/domain/SlackCrusier.java
  src/main/java/kr/co/antoon/common/dto/SlackCrusierDto.java
  src/main/java/kr/co/antoon/common/presentation/HealthController.java
  src/main/java/kr/co/antoon/config/properties/SlackCruiserProperties.java
  src/main/java/kr/co/antoon/cruiser/domain/Cruiser.java
  src/main/java/kr/co/antoon/cruiser/domain/SlackCruiser.java
  src/main/java/kr/co/antoon/cruiser/dto/slack/SlackCruiserRequest.java
  src/main/java/kr/co/antoon/cruiser/dto/slack/SlackCruiserResponse.java
  src/main/java/kr/co/antoon/cruiser/facade/CruiserFacade.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/user/application/UserService.java
Labels: fix, feature

#66 ✨ [Feature/webtoon-64] 웹툰 조회 공통 dto
  src/main/java/kr/co/antoon/webtoon/application/WebtoonGenreService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonPublishDay.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/Platform.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonAllResponse.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonPublishDayRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: feature

#71 🐛 [Improve/db-68] 도메인 정리
  README.md
  src/main/java/kr/co/antoon/batch/recommendation/RecommendationDailyJob.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionLikeService.java
  src/main/java/kr/co/antoon/discussion/domain/Discussion.java
  src/main/java/kr/co/antoon/discussion/domain/DiscussionLike.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
  src/main/java/kr/co/antoon/graph/domain/GraphScoreSnapshot.java
  src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
  src/main/java/kr/co/antoon/recommendation/application/RecommendationService.java
  src/main/java/kr/co/antoon/recommendation/domain/Recommendation.java
  src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
  src/main/java/kr/co/antoon/recommendation/facade/RecommendationFacade.java
  src/main/java/kr/co/antoon/recommendation/infrastructure/RecommendationCountRepository.java
  src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonGenreService.java
  src/main/java/kr/co/antoon/webtoon/converter/WebtoonConverter.java
  src/main/java/kr/co/antoon/webtoon/domain/Webtoon.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonGenre.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/GenreCategory.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonDetailResponse.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
Labels: improve, fix

#73 ✨ [Feature/ranking-65] 랭킹 알고리즘
  scripts/sql/DDL.sql
  src/main/java/kr/co/antoon/batch/cruiser/CruiserHourJob.java
  src/main/java/kr/co/antoon/batch/graph/GraphScoreBatchScheduler.java
  src/main/java/kr/co/antoon/batch/graph/GraphScoreHourJob.java
  src/main/java/kr/co/antoon/cruiser/facade/CruiserFacade.java
  src/main/java/kr/co/antoon/discussion/domain/DiscussionLike.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionLikeFacade.java
  src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
  src/main/java/kr/co/antoon/graph/application/TopRankService.java
  src/main/java/kr/co/antoon/graph/domain/GraphScoreSnapshot.java
  src/main/java/kr/co/antoon/graph/domain/TopRank.java
  src/main/java/kr/co/antoon/graph/domain/vo/GraphStatus.java
  src/main/java/kr/co/antoon/graph/domain/vo/RankReason.java
  src/main/java/kr/co/antoon/graph/dto/TopRankResponse.java
  src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
  src/main/java/kr/co/antoon/graph/facade/TopRankFacade.java
  src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
  src/main/java/kr/co/antoon/graph/infrastructure/TopRankRepository.java
  src/main/java/kr/co/antoon/graph/presentation/TopRankController.java
Labels: fix

#51 ✨ [Feature/discussion 50] 종토방 조회 구현
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/discussion/domain/Discussion.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionCreateResponse.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionReadResponse.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionUpdateResponse.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionLikeController.java
  src/test/java/kr/co/antoon/discussion/application/DiscussionServiceTest.java
  src/test/java/kr/co/antoon/like/application/LikeServiceTest.java
Labels: feature

#81 ✨ [Feature/monitoring-80] 모니터링 서비스 추가 및 배치 수정
  src/main/java/kr/co/antoon/batch/cruiser/CruiserBatchScheduler.java
  src/main/java/kr/co/antoon/batch/cruiser/CruiserHourJob.java
  src/main/java/kr/co/antoon/batch/graph/GraphScoreBatchScheduler.java
  src/main/java/kr/co/antoon/batch/recommendation/RecommendationBatchScheduler.java
  src/main/java/kr/co/antoon/batch/webtoon/WebtoonCrawlingBatchScheduler.java
  src/main/java/kr/co/antoon/common/Utility.java
  src/main/java/kr/co/antoon/cruiser/domain/SlackCruiser.java
  src/main/java/kr/co/antoon/cruiser/dto/slack/SlackCruiserResponse.java
  src/main/java/kr/co/antoon/cruiser/facade/CruiserFacade.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
Labels: improve, fix, feature

#74 ✨ [Feature/day-33] 요일별 웹툰 조회 API
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
  src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonPublishDayService.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonDayResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonPublishDayRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: feature

#85 :sparkles: [Feature/oauth-addInfo-82] 카카오 로그인 시 성별, 연령대 정보 받아오기
  src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
  src/main/java/kr/co/antoon/oauth/presentation/LoginController.java
  src/main/java/kr/co/antoon/user/domain/User.java
Labels: feature

#86 ✨ [Feature/graph-47] 실시간 차트에 대한 리펙토링을 진행합니다
  src/main/java/kr/co/antoon/common/presentation/HealthController.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/discussion/dto/DiscussionCountDto.java
  src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
  src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
  src/main/java/kr/co/antoon/graph/dto/response/TopRankResponse.java
  src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
  src/main/java/kr/co/antoon/graph/facade/TopRankFacade.java
  src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
  src/main/java/kr/co/antoon/graph/presentation/TopRankController.java
  src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
  src/main/java/kr/co/antoon/recommendation/infrastructure/RecommendationCountRepository.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonSnapshotService.java
  src/main/java/kr/co/antoon/webtoon/crawling/NaverWebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
Labels: feature

#91 ✨ [Feature/genres-89] 메인페이지 장르별 조회 API
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/domain/vo/GenreCategory.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonGenreAllResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: feature

#94 ♻️ [Improve/all-system-code-93] 리펙토링 및 기존 코드 문제점 해결
  src/main/java/kr/co/antoon/batch/crawling/CrawlingBatchScheduler.java
  src/main/java/kr/co/antoon/batch/crawling/CrawlingDailyJob.java
  src/main/java/kr/co/antoon/batch/graph/GraphBatchScheduler.java
  src/main/java/kr/co/antoon/batch/graph/GraphHourJob.java
  src/main/java/kr/co/antoon/config/CruiserConfig.java
  src/main/java/kr/co/antoon/crawling/webtoon/KakaoWebtoonCrawling.java
  src/main/java/kr/co/antoon/crawling/webtoon/NaverWebtoonCrawling.java
  src/main/java/kr/co/antoon/crawling/webtoon/WebtoonCrawling.java
  src/main/java/kr/co/antoon/crawling/webtoon/WebtoonCrawlingFactory.java
  src/main/java/kr/co/antoon/cruiser/domain/SlackCruiser.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/graph/dto/response/TopRankResponse.java
  src/main/java/kr/co/antoon/graph/facade/TopRankFacade.java
  src/main/java/kr/co/antoon/oauth/application/AuthService.java
  src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/oauth/application/JwtTokenProvider.java
  src/main/java/kr/co/antoon/oauth/dto/OAuth2Attribute.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/kr/co/antoon/oauth/presentation/AuthController.java
  src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
  src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/dto/response/UserDetailResponse.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/converter/WebtoonConverter.java
  src/main/java/kr/co/antoon/webtoon/domain/Webtoon.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonSnapshot.java
  src/main/java/kr/co/antoon/webtoon/dto/WebtoonDto.java
  src/main/java/kr/co/antoon/webtoon/dto/WebtoonNativeDto.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonCrawlingFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonPublishDayRepository.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: feature

#99 ♻️ [Refactor/webtoon detail] 존재하지 않는 웹툰 조회 시 발생하는 오류 메시지 수정
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
Labels: fix

#103 ✨ [Feature/graph-49] 기간별 웹툰 스코어 조회
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
  src/main/java/kr/co/antoon/graph/domain/vo/Period.java
  src/main/java/kr/co/antoon/graph/dto/response/GraphScoreResponse.java
  src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
  src/main/java/kr/co/antoon/graph/presentation/GraphScoreController.java
Labels: feature

#102 🐛 [Fix/descussion like-101] 댓글 좋아요 수정 및 테스트
  src/main/java/kr/co/antoon/discussion/application/DiscussionLikeService.java
  src/main/java/kr/co/antoon/discussion/domain/DiscussionLike.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionLikeFacade.java
  src/test/java/kr/co/antoon/like/application/LikeServiceTest.java
Labels: fix

#100 :sparkles: [Feature/modify-mypage] 마이페이지(닉네임, 프로필 이미지) 수정 api 구현
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/dto/request/UserDetailRequest.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
Labels: fix

#112 :recycle: [Feature/oauth_redis] redis key값 unique하게 변경
  src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
Labels: improve

#92 :sparkles: [Feature/webtoon-ranking-31] 상승 중인 TOP10 웹툰 조회 API 구현
  src/main/java/kr/co/antoon/common/Utility.java
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/crawling/KakaoWebtoonCrawling.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonRankingAllResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
  src/test/java/kr/co/antoon/webtoon/crawling/KakaoWebtoonCrawlingTest.java
Labels: feature

#116 ⚡️ [Improve/all-109] 성능 개선 및 swagger 수정
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/config/SwaggerConfig.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/dto/WebtoonDayNativeDto.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonDayResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: improve

#117 ♻️ [Refactor/recommendation 115] 탑승해요 하차해요 코드 리팩토링
  src/main/java/kr/co/antoon/recommendation/application/RecommendationCountService.java
  src/main/java/kr/co/antoon/recommendation/application/RecommendationService.java
  src/main/java/kr/co/antoon/recommendation/domain/Recommendation.java
  src/main/java/kr/co/antoon/recommendation/domain/RecommendationCount.java
  src/main/java/kr/co/antoon/recommendation/facade/RecommendationFacade.java
  src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java
Labels: refactor

#120 ⚡️ [Improve/all-113] 앙뚜앙 대격변 3
  src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
  src/main/java/kr/co/antoon/common/Utility.java
  src/main/java/kr/co/antoon/common/util/CommonUtil.java
  src/main/java/kr/co/antoon/common/util/TimeUtil.java
  src/main/java/kr/co/antoon/cruiser/dto/slack/SlackCruiserResponse.java
  src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionLikeController.java
  src/main/java/kr/co/antoon/graph/presentation/GraphScoreController.java
  src/main/java/kr/co/antoon/graph/presentation/TopRankController.java
  src/main/java/kr/co/antoon/oauth/dto/AuthInfo.java
  src/main/java/kr/co/antoon/oauth/presentation/AuthController.java
  src/main/java/kr/co/antoon/recommendation/presentation/RecommendationController.java
  src/main/java/kr/co/antoon/user/application/UserService.java
  src/main/java/kr/co/antoon/user/domain/vo/Role.java
  src/main/java/kr/co/antoon/user/presentation/UserController.java
  src/main/java/kr/co/antoon/webtoon/application/WebtoonService.java
  src/main/java/kr/co/antoon/webtoon/converter/WebtoonConverter.java
  src/main/java/kr/co/antoon/webtoon/dto/query/WebtoonDayNativeDto.java
  src/main/java/kr/co/antoon/webtoon/dto/query/WebtoonGenreBannerNativeDto.java
  src/main/java/kr/co/antoon/webtoon/dto/query/WebtoonGenreNativeDto.java
  src/main/java/kr/co/antoon/webtoon/dto/query/WebtoonNativeDto.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonDayResponse.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonGenreAllResponse.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonGenreResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: improve

#126 🐛[Fix/discussion-118] 댓글 조회 API 권한 수정
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/discussion/application/DiscussionService.java
  src/main/java/kr/co/antoon/discussion/dto/response/DiscussionResponse.java
  src/main/java/kr/co/antoon/discussion/facade/DiscussionFacade.java
  src/main/java/kr/co/antoon/discussion/infrastructure/DiscussionRepository.java
  src/main/java/kr/co/antoon/discussion/presentation/DiscussionController.java
  src/main/java/kr/co/antoon/oauth/config/LoginUserArgumentResolver.java
Labels: fix

#127 ✨ [Feature/age-121] 연령대별 인기 웹툰 조회 mock api 추가
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonAgeResponse.java
  src/main/java/kr/co/antoon/webtoon/facade/WebtoonFacade.java
  src/main/java/kr/co/antoon/webtoon/presentation/WebtoonController.java
Labels: feature

#119 ⚡️ [Feature/login-agree] 로그인 시 정책 동의를 위한 status 변경
  src/main/java/kr/co/antoon/oauth/application/CustomOAuth2UserService.java
  src/main/java/kr/co/antoon/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/kr/co/antoon/user/domain/User.java
  src/main/java/kr/co/antoon/user/domain/vo/Gender.java
  src/main/java/kr/co/antoon/user/infrastructure/UserRepository.java
Labels: improve

#129 ♻️ [Fix/graph-score-124] 그래프 차트 API 분리 작업
  src/main/java/kr/co/antoon/common/dto/SwaggerNote.java
  src/main/java/kr/co/antoon/graph/application/GraphScoreSnapshotService.java
  src/main/java/kr/co/antoon/graph/infrastructure/GraphScoreSnapshotRepository.java
  src/main/java/kr/co/antoon/graph/presentation/GraphScoreController.java
Labels: fix

#133 ⚡️ [Improve/all-125] 앙뚜앙 대격변
  src/main/java/kr/co/antoon/cache/user/UserRedisCacheService.java
  src/main/java/kr/co/antoon/config/ScoreAllocationCriteriaConfig.java
  src/main/java/kr/co/antoon/config/SecurityConfig.java
  src/main/java/kr/co/antoon/config/properties/SlackCruiserProperties.java
  src/main/java/kr/co/antoon/criteria/BasicAllocateScore.java
  src/main/java/kr/co/antoon/criteria/ScoreAllocationCriteria.java
  src/main/java/kr/co/antoon/error/dto/ErrorMessage.java
  src/main/java/kr/co/antoon/graph/facade/GraphScoreFacade.java
  src/main/java/kr/co/antoon/oauth/filter/JwtFilter.java
  src/main/java/kr/co/antoon/webtoon/converter/WebtoonConverter.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonGenre.java
  src/main/java/kr/co/antoon/webtoon/domain/WebtoonPublishDay.java
  src/main/java/kr/co/antoon/webtoon/dto/response/WebtoonGenreResponse.java
  src/main/java/kr/co/antoon/webtoon/infrastructure/WebtoonRepository.java
Labels: improve
